name: Waves
main: gg.aquatic.waves.Waves
version: $version
authors: [ Larkyy ]
api-version: "1.21"
folia-supported: true
loader: gg.aquatic.waves.dependency.DependencyLoader

dependencies:
  server:
    ModelEngine:
      load: BEFORE
      required: false
    BetterModel:
      load: BEFORE
      required: false
    ItemsAdder:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    CraftEngine:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false
    Oraxen:
      load: BEFORE
      required: false
    MythicMobs:
      load: BEFORE
      required: false
    MMOItems:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false